/** Generated by YAKINDU Statechart Tools code generator. */

#ifndef STATECHART_H_
#define STATECHART_H_

#ifdef __cplusplus
extern "C" { 
#endif

/*!
* Forward declaration for the Statechart state machine.
*/
typedef struct Statechart Statechart;

/*!
* Forward declaration of the data structure for the StatechartInternal interface scope.
*/
typedef struct StatechartInternal StatechartInternal;

/*!
* Forward declaration of the data structure for the StatechartIface interface scope.
*/
typedef struct StatechartIface StatechartIface;

/*!
* Forward declaration of the data structure for the StatechartTimeEvents interface scope.
*/
typedef struct StatechartTimeEvents StatechartTimeEvents;

#ifdef __cplusplus
}
#endif

#include "sc_types.h"

#ifdef __cplusplus
extern "C" { 
#endif 

/*! \file Header of the state machine 'Statechart'.
*/

#ifndef STATECHART_EVENTQUEUE_BUFFERSIZE
#define STATECHART_EVENTQUEUE_BUFFERSIZE 20
#endif
#ifndef STATECHART_IN_EVENTQUEUE_BUFFERSIZE
#define STATECHART_IN_EVENTQUEUE_BUFFERSIZE STATECHART_EVENTQUEUE_BUFFERSIZE
#endif
#ifndef SC_INVALID_EVENT_VALUE
#define SC_INVALID_EVENT_VALUE 0
#endif
/*! Define number of states in the state enum */
#define STATECHART_STATE_COUNT 24

/*! Define dimension of the state configuration vector for orthogonal states. */
#define STATECHART_MAX_ORTHOGONAL_STATES 1
/*! Define maximum number of time events that can be active at once */
#define STATECHART_MAX_PARALLEL_TIME_EVENTS 2

/*! Define indices of states in the StateConfVector */
#define SCVI_STATECHART_MAIN_REGION_WAIT4BLE 0
#define SCVI_STATECHART_MAIN_REGION_AUTOSHUTDOWN 0
#define SCVI_STATECHART_MAIN_REGION_SENDGREETINGTEXT 0
#define SCVI_STATECHART_MAIN_REGION_SENDGREETINGTEXT_R1_SENDGREETINGKEYSTROKE 0
#define SCVI_STATECHART_MAIN_REGION_SENDGREETINGTEXT_R1_WAITBEFORESENDINGNEXTGREETINGKEYSTROKE 0
#define SCVI_STATECHART_MAIN_REGION_SENDGREETINGTEXT_R1_GRACEPERIOD 0
#define SCVI_STATECHART_MAIN_REGION_SENDRC5URLTEXTWITHTOUCH 0
#define SCVI_STATECHART_MAIN_REGION_SENDRC5URLTEXTWITHTOUCH_R1_SENDURL1PART 0
#define SCVI_STATECHART_MAIN_REGION_SENDRC5URLTEXTWITHTOUCH_R1_WAIT4NEXTURL1TOUCH 0
#define SCVI_STATECHART_MAIN_REGION_SENDRC5URLTEXTWITHTOUCH_R1_SENDURL2PART 0
#define SCVI_STATECHART_MAIN_REGION_SENDRC5URLTEXTWITHTOUCH_R1_WAIT4NEXTURL2TOUCH 0
#define SCVI_STATECHART_MAIN_REGION_SENDRC5URLTEXTWITHTOUCH_R1_SENDURL3PART 0
#define SCVI_STATECHART_MAIN_REGION_SENDRC5URLTEXTWITHTOUCH_R1_WAIT4NEXTURL3TOUCH 0
#define SCVI_STATECHART_MAIN_REGION_WAIT4RC5MATCH 0
#define SCVI_STATECHART_MAIN_REGION_SENDBRAILLETEXT 0
#define SCVI_STATECHART_MAIN_REGION_SENDBRAILLETEXT_R1_SENDBRAILLECHAR 0
#define SCVI_STATECHART_MAIN_REGION_SENDBRAILLETEXT_R1_WAIT4BRAILLECHARREAD 0
#define SCVI_STATECHART_MAIN_REGION_WAIT4GYROTILT 0
#define SCVI_STATECHART_MAIN_REGION_MORSERC5HINT 0
#define SCVI_STATECHART_MAIN_REGION_MORSERC5HINT_R1_SENDMORSECHAR 0
#define SCVI_STATECHART_MAIN_REGION_MORSERC5HINT_R1_WAIT4MOSECHARREAD 0
#define SCVI_STATECHART_MAIN_REGION_SHOWFINALLAUFSCHRIFT 0
#define SCVI_STATECHART_MAIN_REGION_SHOWFINALLAUFSCHRIFT_R1_SHOWLAUFSCHRIFT 0
#define SCVI_STATECHART_MAIN_REGION_SHOWFINALLAUFSCHRIFT_R1_WAITANDREPEAT 0


/*
 * Enum of event names in the statechart.
 */
typedef enum  {
	Statechart_invalid_event = SC_INVALID_EVENT_VALUE,
	Statechart_BLEconnected,
	Statechart_BLEdisconnected,
	Statechart_Touch1IRQ,
	Statechart_Touch2IRQ,
	Statechart_Touch3IRQ,
	Statechart_KBDstrokeSent,
	Statechart_RC5match,
	Statechart_brailleCharDone,
	Statechart_GYROtilt,
	Statechart_morseCharDone,
	Statechart_Statechart_main_region_wait4BLE_time_event_0,
	Statechart_Statechart_main_region_sendGreetingText_time_event_0,
	Statechart_Statechart_main_region_sendGreetingText_r1_waitBeforeSendingNextGreetingKeystroke_time_event_0,
	Statechart_Statechart_main_region_sendGreetingText_r1_gracePeriod_time_event_0,
	Statechart_Statechart_main_region_sendRC5URLTextWithTouch_time_event_0,
	Statechart_Statechart_main_region_wait4RC5match_time_event_0,
	Statechart_Statechart_main_region_sendBrailleText_r1_wait4BrailleCharRead_time_event_0,
	Statechart_Statechart_main_region_wait4GyroTilt_time_event_0,
	Statechart_Statechart_main_region_wait4GyroTilt_time_event_1,
	Statechart_Statechart_main_region_morseRC5Hint_r1_wait4MoseCharRead_time_event_0,
	Statechart_Statechart_main_region_showFinalLaufschrift_time_event_0,
	Statechart_Statechart_main_region_showFinalLaufschrift_r1_showLaufschrift_time_event_0,
	Statechart_Statechart_main_region_showFinalLaufschrift_r1_waitAndRepeat_time_event_0
} StatechartEventID;

/*
 * Struct that represents a single event.
 */
typedef struct {
	StatechartEventID name;
} statechart_event;

/*
 * Queue that holds the raised events.
 */
typedef struct statechart_eventqueue_s {
	statechart_event *events;
	sc_integer capacity;
	sc_integer pop_index;
	sc_integer push_index;
	sc_integer size;
} statechart_eventqueue;

/*! Enumeration of all states */ 
typedef enum
{
	Statechart_last_state,
	Statechart_main_region_wait4BLE,
	Statechart_main_region_autoShutdown,
	Statechart_main_region_sendGreetingText,
	Statechart_main_region_sendGreetingText_r1_sendGreetingKeyStroke,
	Statechart_main_region_sendGreetingText_r1_waitBeforeSendingNextGreetingKeystroke,
	Statechart_main_region_sendGreetingText_r1_gracePeriod,
	Statechart_main_region_sendRC5URLTextWithTouch,
	Statechart_main_region_sendRC5URLTextWithTouch_r1_sendURL1Part,
	Statechart_main_region_sendRC5URLTextWithTouch_r1_wait4NextURL1touch,
	Statechart_main_region_sendRC5URLTextWithTouch_r1_sendURL2Part,
	Statechart_main_region_sendRC5URLTextWithTouch_r1_wait4NextURL2touch,
	Statechart_main_region_sendRC5URLTextWithTouch_r1_sendURL3Part,
	Statechart_main_region_sendRC5URLTextWithTouch_r1_wait4NextURL3touch,
	Statechart_main_region_wait4RC5match,
	Statechart_main_region_sendBrailleText,
	Statechart_main_region_sendBrailleText_r1_sendBrailleChar,
	Statechart_main_region_sendBrailleText_r1_wait4BrailleCharRead,
	Statechart_main_region_wait4GyroTilt,
	Statechart_main_region_morseRC5Hint,
	Statechart_main_region_morseRC5Hint_r1_sendMorseChar,
	Statechart_main_region_morseRC5Hint_r1_wait4MoseCharRead,
	Statechart_main_region_showFinalLaufschrift,
	Statechart_main_region_showFinalLaufschrift_r1_showLaufschrift,
	Statechart_main_region_showFinalLaufschrift_r1_waitAndRepeat
} StatechartStates;


/*! Type declaration of the data structure for the StatechartInternal interface scope. */
struct StatechartInternal
{
	sc_integer generalTimeout;
	sc_integer greetingWaitTime;
	sc_integer finalShutdownTimeout;
	sc_integer greetingIndex;
	sc_integer url1Index;
	sc_integer url2Index;
	sc_integer url3Index;
	sc_integer brailleIndex;
	sc_integer morseIndex;
	sc_integer laufschriftIndex;
};



/*! Type declaration of the data structure for the StatechartIface interface scope. */
struct StatechartIface
{
	sc_boolean BLEconnected_raised;
	sc_boolean BLEdisconnected_raised;
	sc_boolean Touch1IRQ_raised;
	sc_boolean Touch2IRQ_raised;
	sc_boolean Touch3IRQ_raised;
	sc_boolean KBDstrokeSent_raised;
	sc_boolean RC5match_raised;
	sc_boolean brailleCharDone_raised;
	sc_boolean GYROtilt_raised;
	sc_boolean morseCharDone_raised;
};



/*! Type declaration of the data structure for the StatechartTimeEvents interface scope. */
struct StatechartTimeEvents
{
	sc_boolean statechart_main_region_wait4BLE_tev0_raised;
	sc_boolean statechart_main_region_sendGreetingText_tev0_raised;
	sc_boolean statechart_main_region_sendGreetingText_r1_waitBeforeSendingNextGreetingKeystroke_tev0_raised;
	sc_boolean statechart_main_region_sendGreetingText_r1_gracePeriod_tev0_raised;
	sc_boolean statechart_main_region_sendRC5URLTextWithTouch_tev0_raised;
	sc_boolean statechart_main_region_wait4RC5match_tev0_raised;
	sc_boolean statechart_main_region_sendBrailleText_r1_wait4BrailleCharRead_tev0_raised;
	sc_boolean statechart_main_region_wait4GyroTilt_tev0_raised;
	sc_boolean statechart_main_region_wait4GyroTilt_tev1_raised;
	sc_boolean statechart_main_region_morseRC5Hint_r1_wait4MoseCharRead_tev0_raised;
	sc_boolean statechart_main_region_showFinalLaufschrift_tev0_raised;
	sc_boolean statechart_main_region_showFinalLaufschrift_r1_showLaufschrift_tev0_raised;
	sc_boolean statechart_main_region_showFinalLaufschrift_r1_waitAndRepeat_tev0_raised;
};






/*! 
 * Type declaration of the data structure for the Statechart state machine.
 * This data structure has to be allocated by the client code. 
 */
struct Statechart
{
	StatechartStates stateConfVector[STATECHART_MAX_ORTHOGONAL_STATES];
	StatechartInternal internal;
	StatechartIface iface;
	StatechartTimeEvents timeEvents;
	sc_boolean isExecuting;
	statechart_eventqueue in_event_queue;
	statechart_event in_buffer[STATECHART_IN_EVENTQUEUE_BUFFERSIZE];
};



/*! Initializes the Statechart state machine data structures. Must be called before first usage.*/
extern void statechart_init(Statechart* handle);


/*! Activates the state machine. */
extern void statechart_enter(Statechart* handle);

/*! Deactivates the state machine. */
extern void statechart_exit(Statechart* handle);



/*! Raises a time event. */
extern void statechart_raise_time_event(Statechart* handle, sc_eventid evid);

/*! Raises the in event 'BLEconnected' that is defined in the default interface scope. */ 
extern void statechart_raise_bLEconnected(Statechart* handle);
/*! Raises the in event 'BLEdisconnected' that is defined in the default interface scope. */ 
extern void statechart_raise_bLEdisconnected(Statechart* handle);
/*! Raises the in event 'Touch1IRQ' that is defined in the default interface scope. */ 
extern void statechart_raise_touch1IRQ(Statechart* handle);
/*! Raises the in event 'Touch2IRQ' that is defined in the default interface scope. */ 
extern void statechart_raise_touch2IRQ(Statechart* handle);
/*! Raises the in event 'Touch3IRQ' that is defined in the default interface scope. */ 
extern void statechart_raise_touch3IRQ(Statechart* handle);
/*! Raises the in event 'KBDstrokeSent' that is defined in the default interface scope. */ 
extern void statechart_raise_kBDstrokeSent(Statechart* handle);
/*! Raises the in event 'RC5match' that is defined in the default interface scope. */ 
extern void statechart_raise_rC5match(Statechart* handle);
/*! Raises the in event 'brailleCharDone' that is defined in the default interface scope. */ 
extern void statechart_raise_brailleCharDone(Statechart* handle);
/*! Raises the in event 'GYROtilt' that is defined in the default interface scope. */ 
extern void statechart_raise_gYROtilt(Statechart* handle);
/*! Raises the in event 'morseCharDone' that is defined in the default interface scope. */ 
extern void statechart_raise_morseCharDone(Statechart* handle);

/*!
 * Checks whether the state machine is active (until 2.4.1 this method was used for states).
 * A state machine is active if it was entered. It is inactive if it has not been entered at all or if it has been exited.
 */
extern sc_boolean statechart_is_active(const Statechart* handle);

/*!
 * Checks if all active states are final. 
 * If there are no active states then the state machine is considered being inactive. In this case this method returns false.
 */
extern sc_boolean statechart_is_final(const Statechart* handle);

/*! Checks if the specified state is active (until 2.4.1 the used method for states was called isActive()). */
extern sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state);


#ifdef __cplusplus
}
#endif 

#endif /* STATECHART_H_ */
