/** Generated by YAKINDU Statechart Tools code generator. */


#include "sc_types.h"

#include "Statechart.h"

/*! \file Implementation of the state machine 'Statechart'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enseq_main_region_wait4BLE_default(Statechart* handle);
static void enseq_main_region_sendGreeting_default(Statechart* handle);
static void enseq_main_region_autoShutdown_default(Statechart* handle);
static void enseq_main_region_default(Statechart* handle);
static void exseq_main_region_wait4BLE(Statechart* handle);
static void exseq_main_region_sendGreeting(Statechart* handle);
static void exseq_main_region_autoShutdown(Statechart* handle);
static void exseq_main_region(Statechart* handle);
static void react_main_region__entry_Default(Statechart* handle);

/*! State machine reactions. */
static sc_boolean react(Statechart* handle);

/*! The reactions of state wait4BLE. */
static sc_boolean main_region_wait4BLE_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state sendGreeting. */
static sc_boolean main_region_sendGreeting_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state autoShutdown. */
static sc_boolean main_region_autoShutdown_react(Statechart* handle, const sc_boolean try_transition);


static void clearInEvents(Statechart* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Statechart* handle);



static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity);
static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq);
static void statechart_event_init(statechart_event * ev, StatechartEventID name);
static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq);
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev);
static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name);
static void statechart_dispatch_event(Statechart* handle, const statechart_event * event);
static statechart_event statechart_get_next_event(Statechart* handle);
static void statechart_dispatch_next_event(Statechart* handle);


void statechart_init(Statechart* handle)
{
	sc_integer i;
	
	for (i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Statechart_last_state;
	}
	
	
	handle->stateConfVectorPosition = 0;
	
	clearInEvents(handle);
	
	sc_observable_init(&handle->iface.sendTLCbraille);
	sc_observable_init(&handle->iface.sendTLCmorse);
	sc_observable_init(&handle->iface.sendKBDstroke);
	
	
	handle->isExecuting = bool_false;
	statechart_eventqueue_init(&handle->in_event_queue, handle->in_buffer, STATECHART_IN_EVENTQUEUE_BUFFERSIZE);
}

void statechart_enter(Statechart* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart Statechart */
	enseq_main_region_default(handle);
	handle->isExecuting = bool_false;
}

void statechart_exit(Statechart* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart Statechart */
	exseq_main_region(handle);
	handle->isExecuting = bool_false;
}


sc_boolean statechart_is_active(const Statechart* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Statechart_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean statechart_is_final(const Statechart* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Statechart_main_region_wait4BLE :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_WAIT4BLE] == Statechart_main_region_wait4BLE
			);
			break;
		case Statechart_main_region_sendGreeting :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SENDGREETING] == Statechart_main_region_sendGreeting
			);
			break;
		case Statechart_main_region_autoShutdown :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_AUTOSHUTDOWN] == Statechart_main_region_autoShutdown
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clearInEvents(Statechart* handle)
{
	handle->iface.BLEconnected_raised = bool_false;
	handle->iface.BLEdisconnected_raised = bool_false;
	handle->iface.Touch1press_raised = bool_false;
	handle->iface.Touch2press_raised = bool_false;
	handle->iface.Touch3press_raised = bool_false;
	handle->iface.RC5match_raised = bool_false;
	handle->iface.GYROtilt_raised = bool_false;
	handle->iface.KBDstrokeSent_raised = bool_false;
}

static void run_cycle(Statechart* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	statechart_dispatch_next_event(handle);
	do
	{ 
		for (handle->stateConfVectorPosition = 0;
			handle->stateConfVectorPosition < STATECHART_MAX_ORTHOGONAL_STATES;
			handle->stateConfVectorPosition++)
			{
				
			switch (handle->stateConfVector[handle->stateConfVectorPosition])
			{
			case Statechart_main_region_wait4BLE:
			{
				main_region_wait4BLE_react(handle, bool_true);
				break;
			}
			case Statechart_main_region_sendGreeting:
			{
				main_region_sendGreeting_react(handle, bool_true);
				break;
			}
			case Statechart_main_region_autoShutdown:
			{
				main_region_autoShutdown_react(handle, bool_true);
				break;
			}
			default:
				break;
			}
		}
		clearInEvents(handle);
		statechart_dispatch_next_event(handle);
	} while ((((((((handle->iface.BLEconnected_raised == bool_true) || (handle->iface.BLEdisconnected_raised == bool_true)) || (handle->iface.Touch1press_raised == bool_true)) || (handle->iface.Touch2press_raised == bool_true)) || (handle->iface.Touch3press_raised == bool_true)) || (handle->iface.RC5match_raised == bool_true)) || (handle->iface.GYROtilt_raised == bool_true)) || (handle->iface.KBDstrokeSent_raised == bool_true));
	handle->isExecuting = bool_false;
}


void statechart_raise_bLEconnected(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_BLEconnected);
	run_cycle(handle);
}

void statechart_raise_bLEdisconnected(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_BLEdisconnected);
	run_cycle(handle);
}

void statechart_raise_touch1press(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_Touch1press);
	run_cycle(handle);
}

void statechart_raise_touch2press(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_Touch2press);
	run_cycle(handle);
}

void statechart_raise_touch3press(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_Touch3press);
	run_cycle(handle);
}

void statechart_raise_rC5match(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_RC5match);
	run_cycle(handle);
}

void statechart_raise_gYROtilt(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_GYROtilt);
	run_cycle(handle);
}

void statechart_raise_kBDstrokeSent(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_KBDstrokeSent);
	run_cycle(handle);
}


sc_observable* statechart_get_sendTLCbraille(Statechart* handle)
{
	return &handle->iface.sendTLCbraille;
}
sc_observable* statechart_get_sendTLCmorse(Statechart* handle)
{
	return &handle->iface.sendTLCmorse;
}
sc_observable* statechart_get_sendKBDstroke(Statechart* handle)
{
	return &handle->iface.sendKBDstroke;
}


/* implementations of all internal functions */

/* 'default' enter sequence for state wait4BLE */
static void enseq_main_region_wait4BLE_default(Statechart* handle)
{
	/* 'default' enter sequence for state wait4BLE */
	handle->stateConfVector[0] = Statechart_main_region_wait4BLE;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state sendGreeting */
static void enseq_main_region_sendGreeting_default(Statechart* handle)
{
	/* 'default' enter sequence for state sendGreeting */
	handle->stateConfVector[0] = Statechart_main_region_sendGreeting;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state autoShutdown */
static void enseq_main_region_autoShutdown_default(Statechart* handle)
{
	/* 'default' enter sequence for state autoShutdown */
	handle->stateConfVector[0] = Statechart_main_region_autoShutdown;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Statechart* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state wait4BLE */
static void exseq_main_region_wait4BLE(Statechart* handle)
{
	/* Default exit sequence for state wait4BLE */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state sendGreeting */
static void exseq_main_region_sendGreeting(Statechart* handle)
{
	/* Default exit sequence for state sendGreeting */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state autoShutdown */
static void exseq_main_region_autoShutdown(Statechart* handle)
{
	/* Default exit sequence for state autoShutdown */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for region main region */
static void exseq_main_region(Statechart* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of Statechart.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_wait4BLE :
		{
			exseq_main_region_wait4BLE(handle);
			break;
		}
		case Statechart_main_region_sendGreeting :
		{
			exseq_main_region_sendGreeting(handle);
			break;
		}
		case Statechart_main_region_autoShutdown :
		{
			exseq_main_region_autoShutdown(handle);
			break;
		}
		default: break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_wait4BLE_default(handle);
}


static sc_boolean react(Statechart* handle)
{
	/* State machine reactions. */
	SC_UNUSED(handle);
	return bool_false;
}

static sc_boolean main_region_wait4BLE_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state wait4BLE. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->iface.BLEconnected_raised == bool_true)
		{ 
			exseq_main_region_wait4BLE(handle);
			enseq_main_region_sendGreeting_default(handle);
			react(handle);
		}  else
		{
			did_transition = bool_false;
		}
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} return did_transition;
}

static sc_boolean main_region_sendGreeting_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state sendGreeting. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->iface.BLEdisconnected_raised == bool_true)
		{ 
			exseq_main_region_sendGreeting(handle);
			enseq_main_region_autoShutdown_default(handle);
			react(handle);
		}  else
		{
			did_transition = bool_false;
		}
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} return did_transition;
}

static sc_boolean main_region_autoShutdown_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state autoShutdown. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		did_transition = bool_false;
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} return did_transition;
}




static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq)
{
	return eq->size;
}

static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq)
{
	statechart_event event;
	if(statechart_eventqueue_size(eq) <= 0) {
		statechart_event_init(&event, Statechart_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev)
{
	if(statechart_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void statechart_event_init(statechart_event * ev, StatechartEventID name)
{
	ev->name = name;
}

static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name)
{
	statechart_event event;
	statechart_event_init(&event, name);
	statechart_eventqueue_push(eq, event);
}

static void statechart_dispatch_event(Statechart* handle, const statechart_event * event) {
	switch(event->name) {
		case Statechart_BLEconnected:
		{
			handle->iface.BLEconnected_raised = bool_true;
			break;
		}
		case Statechart_BLEdisconnected:
		{
			handle->iface.BLEdisconnected_raised = bool_true;
			break;
		}
		case Statechart_Touch1press:
		{
			handle->iface.Touch1press_raised = bool_true;
			break;
		}
		case Statechart_Touch2press:
		{
			handle->iface.Touch2press_raised = bool_true;
			break;
		}
		case Statechart_Touch3press:
		{
			handle->iface.Touch3press_raised = bool_true;
			break;
		}
		case Statechart_RC5match:
		{
			handle->iface.RC5match_raised = bool_true;
			break;
		}
		case Statechart_GYROtilt:
		{
			handle->iface.GYROtilt_raised = bool_true;
			break;
		}
		case Statechart_KBDstrokeSent:
		{
			handle->iface.KBDstrokeSent_raised = bool_true;
			break;
		}
		default:
			break;
	}
}

static statechart_event statechart_get_next_event(Statechart* handle)
{
	statechart_event next_event;
	statechart_event_init(&next_event, Statechart_invalid_event);
	if(statechart_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = statechart_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static void statechart_dispatch_next_event(Statechart* handle)
{
	statechart_event nextEvent;
	nextEvent = statechart_get_next_event(handle);
	statechart_dispatch_event(handle, &nextEvent);
}
