/** Generated by YAKINDU Statechart Tools code generator. */


#include "sc_types.h"

#include "Statechart.h"
#include "Statechart_required.h"

/*! \file Implementation of the state machine 'Statechart'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enact_main_region_wait4BLE(Statechart* handle);
static void enact_main_region_autoShutdown(Statechart* handle);
static void enact_main_region_sendGreetingText(Statechart* handle);
static void enact_main_region_sendGreetingText_r1_sendGreetingKeyStroke(Statechart* handle);
static void enact_main_region_sendGreetingText_r1_gracePeriod(Statechart* handle);
static void enact_main_region_sendRC5URLTextWithTouch(Statechart* handle);
static void enact_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke(Statechart* handle);
static void enact_main_region_wait4RC5match(Statechart* handle);
static void enact_main_region_sendBrailleText_r1_sendBrailleChar(Statechart* handle);
static void enact_main_region_wait4GyroTilt(Statechart* handle);
static void enact_main_region_morseFinalURL(Statechart* handle);
static void enact_main_region_morseFinalURL_r1_sendMorseChar(Statechart* handle);
static void exact_main_region_wait4BLE(Statechart* handle);
static void exact_main_region_sendGreetingText(Statechart* handle);
static void exact_main_region_sendGreetingText_r1_sendGreetingKeyStroke(Statechart* handle);
static void exact_main_region_sendGreetingText_r1_gracePeriod(Statechart* handle);
static void exact_main_region_sendRC5URLTextWithTouch(Statechart* handle);
static void exact_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke(Statechart* handle);
static void exact_main_region_wait4RC5match(Statechart* handle);
static void exact_main_region_wait4GyroTilt(Statechart* handle);
static void exact_main_region_morseFinalURL_r1_sendMorseChar(Statechart* handle);
static void enseq_main_region_wait4BLE_default(Statechart* handle);
static void enseq_main_region_autoShutdown_default(Statechart* handle);
static void enseq_main_region_sendGreetingText_default(Statechart* handle);
static void enseq_main_region_sendGreetingText_r1_sendGreetingKeyStroke_default(Statechart* handle);
static void enseq_main_region_sendGreetingText_r1_waitForGreetingKeystrokeSent_default(Statechart* handle);
static void enseq_main_region_sendGreetingText_r1_gracePeriod_default(Statechart* handle);
static void enseq_main_region_sendRC5URLTextWithTouch_default(Statechart* handle);
static void enseq_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke_default(Statechart* handle);
static void enseq_main_region_sendRC5URLTextWithTouch_r1_wait4URLKeyStrokeSent_default(Statechart* handle);
static void enseq_main_region_sendRC5URLTextWithTouch_r1_wait4NextURLtouch_default(Statechart* handle);
static void enseq_main_region_wait4RC5match_default(Statechart* handle);
static void enseq_main_region_sendBrailleText_default(Statechart* handle);
static void enseq_main_region_sendBrailleText_r1_sendBrailleChar_default(Statechart* handle);
static void enseq_main_region_wait4GyroTilt_default(Statechart* handle);
static void enseq_main_region_morseFinalURL_default(Statechart* handle);
static void enseq_main_region_morseFinalURL_r1_sendMorseChar_default(Statechart* handle);
static void enseq_main_region_morseFinalURL_r1_prepareNextChar_default(Statechart* handle);
static void enseq_main_region_showFinalLaufschrift_default(Statechart* handle);
static void enseq_main_region_showFinalLaufschrift_r1_showLaufschrift_default(Statechart* handle);
static void enseq_main_region_default(Statechart* handle);
static void enseq_main_region_sendGreetingText_r1_default(Statechart* handle);
static void enseq_main_region_sendRC5URLTextWithTouch_r1_default(Statechart* handle);
static void enseq_main_region_sendBrailleText_r1_default(Statechart* handle);
static void enseq_main_region_morseFinalURL_r1_default(Statechart* handle);
static void enseq_main_region_showFinalLaufschrift_r1_default(Statechart* handle);
static void exseq_main_region_wait4BLE(Statechart* handle);
static void exseq_main_region_autoShutdown(Statechart* handle);
static void exseq_main_region_sendGreetingText(Statechart* handle);
static void exseq_main_region_sendGreetingText_r1_sendGreetingKeyStroke(Statechart* handle);
static void exseq_main_region_sendGreetingText_r1_waitForGreetingKeystrokeSent(Statechart* handle);
static void exseq_main_region_sendGreetingText_r1_gracePeriod(Statechart* handle);
static void exseq_main_region_sendRC5URLTextWithTouch(Statechart* handle);
static void exseq_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke(Statechart* handle);
static void exseq_main_region_sendRC5URLTextWithTouch_r1_wait4URLKeyStrokeSent(Statechart* handle);
static void exseq_main_region_sendRC5URLTextWithTouch_r1_wait4NextURLtouch(Statechart* handle);
static void exseq_main_region_wait4RC5match(Statechart* handle);
static void exseq_main_region_sendBrailleText(Statechart* handle);
static void exseq_main_region_sendBrailleText_r1_sendBrailleChar(Statechart* handle);
static void exseq_main_region_wait4GyroTilt(Statechart* handle);
static void exseq_main_region_morseFinalURL(Statechart* handle);
static void exseq_main_region_morseFinalURL_r1_sendMorseChar(Statechart* handle);
static void exseq_main_region_morseFinalURL_r1_prepareNextChar(Statechart* handle);
static void exseq_main_region_showFinalLaufschrift_r1_showLaufschrift(Statechart* handle);
static void exseq_main_region(Statechart* handle);
static void exseq_main_region_sendGreetingText_r1(Statechart* handle);
static void exseq_main_region_sendRC5URLTextWithTouch_r1(Statechart* handle);
static void exseq_main_region_sendBrailleText_r1(Statechart* handle);
static void exseq_main_region_morseFinalURL_r1(Statechart* handle);
static void react_main_region__entry_Default(Statechart* handle);
static void react_main_region_sendGreetingText_r1__entry_Default(Statechart* handle);
static void react_main_region_sendRC5URLTextWithTouch_r1__entry_Default(Statechart* handle);
static void react_main_region_sendBrailleText_r1__entry_Default(Statechart* handle);
static void react_main_region_morseFinalURL_r1__entry_Default(Statechart* handle);
static void react_main_region_showFinalLaufschrift_r1__entry_Default(Statechart* handle);

/*! State machine reactions. */
static sc_boolean react(Statechart* handle);

/*! The reactions of state wait4BLE. */
static sc_boolean main_region_wait4BLE_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state autoShutdown. */
static sc_boolean main_region_autoShutdown_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state sendGreetingText. */
static sc_boolean main_region_sendGreetingText_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state sendGreetingKeyStroke. */
static sc_boolean main_region_sendGreetingText_r1_sendGreetingKeyStroke_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state waitForGreetingKeystrokeSent. */
static sc_boolean main_region_sendGreetingText_r1_waitForGreetingKeystrokeSent_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state gracePeriod. */
static sc_boolean main_region_sendGreetingText_r1_gracePeriod_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state sendRC5URLTextWithTouch. */
static sc_boolean main_region_sendRC5URLTextWithTouch_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state sendURLKeyStroke. */
static sc_boolean main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state wait4URLKeyStrokeSent. */
static sc_boolean main_region_sendRC5URLTextWithTouch_r1_wait4URLKeyStrokeSent_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state wait4NextURLtouch. */
static sc_boolean main_region_sendRC5URLTextWithTouch_r1_wait4NextURLtouch_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state wait4RC5match. */
static sc_boolean main_region_wait4RC5match_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state sendBrailleText. */
static sc_boolean main_region_sendBrailleText_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state sendBrailleChar. */
static sc_boolean main_region_sendBrailleText_r1_sendBrailleChar_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state wait4GyroTilt. */
static sc_boolean main_region_wait4GyroTilt_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state morseFinalURL. */
static sc_boolean main_region_morseFinalURL_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state sendMorseChar. */
static sc_boolean main_region_morseFinalURL_r1_sendMorseChar_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state prepareNextChar. */
static sc_boolean main_region_morseFinalURL_r1_prepareNextChar_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state showFinalLaufschrift. */
static sc_boolean main_region_showFinalLaufschrift_react(Statechart* handle, const sc_boolean try_transition);

/*! The reactions of state showLaufschrift. */
static sc_boolean main_region_showFinalLaufschrift_r1_showLaufschrift_react(Statechart* handle, const sc_boolean try_transition);


static void clearInEvents(Statechart* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Statechart* handle);



static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity);
static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq);
static void statechart_event_init(statechart_event * ev, StatechartEventID name);
static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq);
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev);
static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name);
static void statechart_dispatch_event(Statechart* handle, const statechart_event * event);
static statechart_event statechart_get_next_event(Statechart* handle);
static void statechart_dispatch_next_event(Statechart* handle);
static StatechartEventID statechart_get_timed_event_name(Statechart* handle, sc_eventid evid);
static void statechart_event_value_init(statechart_event * ev, StatechartEventID name, void * value);
static void statechart_add_value_event_to_queue(statechart_eventqueue * eq, StatechartEventID name, void * value);


void statechart_init(Statechart* handle)
{
	sc_integer i;
	
	for (i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Statechart_last_state;
	}
	
	
	handle->stateConfVectorPosition = 0;
	
	clearInEvents(handle);
	
	
	/* Default init sequence for statechart Statechart */
	handle->internal.generalTimeout = (5 * 60);
	handle->internal.greetingIndex = 0;
	handle->internal.morseIndex = 0;
	
	handle->isExecuting = bool_false;
	statechart_eventqueue_init(&handle->in_event_queue, handle->in_buffer, STATECHART_IN_EVENTQUEUE_BUFFERSIZE);
}

void statechart_enter(Statechart* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart Statechart */
	enseq_main_region_default(handle);
	handle->isExecuting = bool_false;
}

void statechart_exit(Statechart* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart Statechart */
	exseq_main_region(handle);
	handle->isExecuting = bool_false;
}


sc_boolean statechart_is_active(const Statechart* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Statechart_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean statechart_is_final(const Statechart* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

void statechart_raise_time_event(Statechart* handle, sc_eventid evid)
{
	if ( ((sc_intptr_t)evid) >= ((sc_intptr_t)&(handle->timeEvents))
		&&  ((sc_intptr_t)evid) < ((sc_intptr_t)&(handle->timeEvents)) + (unsigned)sizeof(StatechartTimeEvents))
	{
		statechart_add_event_to_queue(&(handle->in_event_queue), statechart_get_timed_event_name(handle, evid));
		run_cycle(handle);
	}
}

sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Statechart_main_region_wait4BLE :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_WAIT4BLE] == Statechart_main_region_wait4BLE
			);
			break;
		case Statechart_main_region_autoShutdown :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_AUTOSHUTDOWN] == Statechart_main_region_autoShutdown
			);
			break;
		case Statechart_main_region_sendGreetingText :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SENDGREETINGTEXT] >= Statechart_main_region_sendGreetingText
				&& handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SENDGREETINGTEXT] <= Statechart_main_region_sendGreetingText_r1_gracePeriod);
			break;
		case Statechart_main_region_sendGreetingText_r1_sendGreetingKeyStroke :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SENDGREETINGTEXT_R1_SENDGREETINGKEYSTROKE] == Statechart_main_region_sendGreetingText_r1_sendGreetingKeyStroke
			);
			break;
		case Statechart_main_region_sendGreetingText_r1_waitForGreetingKeystrokeSent :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SENDGREETINGTEXT_R1_WAITFORGREETINGKEYSTROKESENT] == Statechart_main_region_sendGreetingText_r1_waitForGreetingKeystrokeSent
			);
			break;
		case Statechart_main_region_sendGreetingText_r1_gracePeriod :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SENDGREETINGTEXT_R1_GRACEPERIOD] == Statechart_main_region_sendGreetingText_r1_gracePeriod
			);
			break;
		case Statechart_main_region_sendRC5URLTextWithTouch :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SENDRC5URLTEXTWITHTOUCH] >= Statechart_main_region_sendRC5URLTextWithTouch
				&& handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SENDRC5URLTEXTWITHTOUCH] <= Statechart_main_region_sendRC5URLTextWithTouch_r1_wait4NextURLtouch);
			break;
		case Statechart_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SENDRC5URLTEXTWITHTOUCH_R1_SENDURLKEYSTROKE] == Statechart_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke
			);
			break;
		case Statechart_main_region_sendRC5URLTextWithTouch_r1_wait4URLKeyStrokeSent :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SENDRC5URLTEXTWITHTOUCH_R1_WAIT4URLKEYSTROKESENT] == Statechart_main_region_sendRC5URLTextWithTouch_r1_wait4URLKeyStrokeSent
			);
			break;
		case Statechart_main_region_sendRC5URLTextWithTouch_r1_wait4NextURLtouch :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SENDRC5URLTEXTWITHTOUCH_R1_WAIT4NEXTURLTOUCH] == Statechart_main_region_sendRC5URLTextWithTouch_r1_wait4NextURLtouch
			);
			break;
		case Statechart_main_region_wait4RC5match :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_WAIT4RC5MATCH] == Statechart_main_region_wait4RC5match
			);
			break;
		case Statechart_main_region_sendBrailleText :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SENDBRAILLETEXT] >= Statechart_main_region_sendBrailleText
				&& handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SENDBRAILLETEXT] <= Statechart_main_region_sendBrailleText_r1_sendBrailleChar);
			break;
		case Statechart_main_region_sendBrailleText_r1_sendBrailleChar :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SENDBRAILLETEXT_R1_SENDBRAILLECHAR] == Statechart_main_region_sendBrailleText_r1_sendBrailleChar
			);
			break;
		case Statechart_main_region_wait4GyroTilt :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_WAIT4GYROTILT] == Statechart_main_region_wait4GyroTilt
			);
			break;
		case Statechart_main_region_morseFinalURL :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_MORSEFINALURL] >= Statechart_main_region_morseFinalURL
				&& handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_MORSEFINALURL] <= Statechart_main_region_morseFinalURL_r1_prepareNextChar);
			break;
		case Statechart_main_region_morseFinalURL_r1_sendMorseChar :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_MORSEFINALURL_R1_SENDMORSECHAR] == Statechart_main_region_morseFinalURL_r1_sendMorseChar
			);
			break;
		case Statechart_main_region_morseFinalURL_r1_prepareNextChar :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_MORSEFINALURL_R1_PREPARENEXTCHAR] == Statechart_main_region_morseFinalURL_r1_prepareNextChar
			);
			break;
		case Statechart_main_region_showFinalLaufschrift :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SHOWFINALLAUFSCHRIFT] >= Statechart_main_region_showFinalLaufschrift
				&& handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SHOWFINALLAUFSCHRIFT] <= Statechart_main_region_showFinalLaufschrift_r1_showLaufschrift);
			break;
		case Statechart_main_region_showFinalLaufschrift_r1_showLaufschrift :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_SHOWFINALLAUFSCHRIFT_R1_SHOWLAUFSCHRIFT] == Statechart_main_region_showFinalLaufschrift_r1_showLaufschrift
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clearInEvents(Statechart* handle)
{
	handle->iface.BLEconnected_raised = bool_false;
	handle->iface.BLEdisconnected_raised = bool_false;
	handle->iface.TouchIRQ_raised = bool_false;
	handle->iface.KBDstrokeSent_raised = bool_false;
	handle->iface.URLstringDone_raised = bool_false;
	handle->iface.RC5match_raised = bool_false;
	handle->iface.brailleCharSent_raised = bool_false;
	handle->iface.brailleStringDone_raised = bool_false;
	handle->iface.GYROtilt_raised = bool_false;
	handle->iface.morseStringDone_raised = bool_false;
	handle->timeEvents.statechart_main_region_wait4BLE_tev0_raised = bool_false;
	handle->timeEvents.statechart_main_region_sendGreetingText_tev0_raised = bool_false;
	handle->timeEvents.statechart_main_region_sendGreetingText_r1_sendGreetingKeyStroke_tev0_raised = bool_false;
	handle->timeEvents.statechart_main_region_sendGreetingText_r1_gracePeriod_tev0_raised = bool_false;
	handle->timeEvents.statechart_main_region_sendRC5URLTextWithTouch_tev0_raised = bool_false;
	handle->timeEvents.statechart_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke_tev0_raised = bool_false;
	handle->timeEvents.statechart_main_region_wait4RC5match_tev0_raised = bool_false;
	handle->timeEvents.statechart_main_region_wait4GyroTilt_tev0_raised = bool_false;
	handle->timeEvents.statechart_main_region_morseFinalURL_r1_sendMorseChar_tev0_raised = bool_false;
}

static void run_cycle(Statechart* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	statechart_dispatch_next_event(handle);
	do
	{ 
		for (handle->stateConfVectorPosition = 0;
			handle->stateConfVectorPosition < STATECHART_MAX_ORTHOGONAL_STATES;
			handle->stateConfVectorPosition++)
			{
				
			switch (handle->stateConfVector[handle->stateConfVectorPosition])
			{
			case Statechart_main_region_wait4BLE:
			{
				main_region_wait4BLE_react(handle, bool_true);
				break;
			}
			case Statechart_main_region_autoShutdown:
			{
				main_region_autoShutdown_react(handle, bool_true);
				break;
			}
			case Statechart_main_region_sendGreetingText_r1_sendGreetingKeyStroke:
			{
				main_region_sendGreetingText_r1_sendGreetingKeyStroke_react(handle, bool_true);
				break;
			}
			case Statechart_main_region_sendGreetingText_r1_waitForGreetingKeystrokeSent:
			{
				main_region_sendGreetingText_r1_waitForGreetingKeystrokeSent_react(handle, bool_true);
				break;
			}
			case Statechart_main_region_sendGreetingText_r1_gracePeriod:
			{
				main_region_sendGreetingText_r1_gracePeriod_react(handle, bool_true);
				break;
			}
			case Statechart_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke:
			{
				main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke_react(handle, bool_true);
				break;
			}
			case Statechart_main_region_sendRC5URLTextWithTouch_r1_wait4URLKeyStrokeSent:
			{
				main_region_sendRC5URLTextWithTouch_r1_wait4URLKeyStrokeSent_react(handle, bool_true);
				break;
			}
			case Statechart_main_region_sendRC5URLTextWithTouch_r1_wait4NextURLtouch:
			{
				main_region_sendRC5URLTextWithTouch_r1_wait4NextURLtouch_react(handle, bool_true);
				break;
			}
			case Statechart_main_region_wait4RC5match:
			{
				main_region_wait4RC5match_react(handle, bool_true);
				break;
			}
			case Statechart_main_region_sendBrailleText_r1_sendBrailleChar:
			{
				main_region_sendBrailleText_r1_sendBrailleChar_react(handle, bool_true);
				break;
			}
			case Statechart_main_region_wait4GyroTilt:
			{
				main_region_wait4GyroTilt_react(handle, bool_true);
				break;
			}
			case Statechart_main_region_morseFinalURL_r1_sendMorseChar:
			{
				main_region_morseFinalURL_r1_sendMorseChar_react(handle, bool_true);
				break;
			}
			case Statechart_main_region_morseFinalURL_r1_prepareNextChar:
			{
				main_region_morseFinalURL_r1_prepareNextChar_react(handle, bool_true);
				break;
			}
			case Statechart_main_region_showFinalLaufschrift_r1_showLaufschrift:
			{
				main_region_showFinalLaufschrift_r1_showLaufschrift_react(handle, bool_true);
				break;
			}
			default:
				break;
			}
		}
		clearInEvents(handle);
		statechart_dispatch_next_event(handle);
	} while (((((((((((((((((((handle->iface.BLEconnected_raised == bool_true) || (handle->iface.BLEdisconnected_raised == bool_true)) || (handle->iface.TouchIRQ_raised == bool_true)) || (handle->iface.KBDstrokeSent_raised == bool_true)) || (handle->iface.URLstringDone_raised == bool_true)) || (handle->iface.RC5match_raised == bool_true)) || (handle->iface.brailleCharSent_raised == bool_true)) || (handle->iface.brailleStringDone_raised == bool_true)) || (handle->iface.GYROtilt_raised == bool_true)) || (handle->iface.morseStringDone_raised == bool_true)) || (handle->timeEvents.statechart_main_region_wait4BLE_tev0_raised == bool_true)) || (handle->timeEvents.statechart_main_region_sendGreetingText_tev0_raised == bool_true)) || (handle->timeEvents.statechart_main_region_sendGreetingText_r1_sendGreetingKeyStroke_tev0_raised == bool_true)) || (handle->timeEvents.statechart_main_region_sendGreetingText_r1_gracePeriod_tev0_raised == bool_true)) || (handle->timeEvents.statechart_main_region_sendRC5URLTextWithTouch_tev0_raised == bool_true)) || (handle->timeEvents.statechart_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke_tev0_raised == bool_true)) || (handle->timeEvents.statechart_main_region_wait4RC5match_tev0_raised == bool_true)) || (handle->timeEvents.statechart_main_region_wait4GyroTilt_tev0_raised == bool_true)) || (handle->timeEvents.statechart_main_region_morseFinalURL_r1_sendMorseChar_tev0_raised == bool_true));
	handle->isExecuting = bool_false;
}


void statechart_raise_bLEconnected(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_BLEconnected);
	run_cycle(handle);
}

void statechart_raise_bLEdisconnected(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_BLEdisconnected);
	run_cycle(handle);
}

void statechart_raise_touchIRQ(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_TouchIRQ);
	run_cycle(handle);
}

void statechart_raise_kBDstrokeSent(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_KBDstrokeSent);
	run_cycle(handle);
}

void statechart_raise_uRLstringDone(Statechart* handle, sc_integer value)
{
	statechart_add_value_event_to_queue(&(handle->in_event_queue), Statechart_URLstringDone, &value);
	run_cycle(handle);
}

void statechart_raise_rC5match(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_RC5match);
	run_cycle(handle);
}

void statechart_raise_brailleCharSent(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_brailleCharSent);
	run_cycle(handle);
}

void statechart_raise_brailleStringDone(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_brailleStringDone);
	run_cycle(handle);
}

void statechart_raise_gYROtilt(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_GYROtilt);
	run_cycle(handle);
}

void statechart_raise_morseStringDone(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_morseStringDone);
	run_cycle(handle);
}




/* implementations of all internal functions */

/* Entry action for state 'wait4BLE'. */
static void enact_main_region_wait4BLE(Statechart* handle)
{
	/* Entry action for state 'wait4BLE'. */
	statechart_set_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_wait4BLE_tev0_raised) , (handle->internal.generalTimeout * 1000), bool_false);
}

/* Entry action for state 'autoShutdown'. */
static void enact_main_region_autoShutdown(Statechart* handle)
{
	/* Entry action for state 'autoShutdown'. */
	statechart_shutDownSystem(handle);
}

/* Entry action for state 'sendGreetingText'. */
static void enact_main_region_sendGreetingText(Statechart* handle)
{
	/* Entry action for state 'sendGreetingText'. */
	statechart_set_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_sendGreetingText_tev0_raised) , (handle->internal.generalTimeout * 1000), bool_false);
	handle->internal.greetingIndex = 0;
}

/* Entry action for state 'sendGreetingKeyStroke'. */
static void enact_main_region_sendGreetingText_r1_sendGreetingKeyStroke(Statechart* handle)
{
	/* Entry action for state 'sendGreetingKeyStroke'. */
	statechart_set_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_sendGreetingText_r1_sendGreetingKeyStroke_tev0_raised) , 100, bool_false);
	statechart_sendKBDstroke(handle, 0, handle->internal.greetingIndex++);
}

/* Entry action for state 'gracePeriod'. */
static void enact_main_region_sendGreetingText_r1_gracePeriod(Statechart* handle)
{
	/* Entry action for state 'gracePeriod'. */
	statechart_set_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_sendGreetingText_r1_gracePeriod_tev0_raised) , (60 * 1000), bool_false);
}

/* Entry action for state 'sendRC5URLTextWithTouch'. */
static void enact_main_region_sendRC5URLTextWithTouch(Statechart* handle)
{
	/* Entry action for state 'sendRC5URLTextWithTouch'. */
	statechart_set_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_sendRC5URLTextWithTouch_tev0_raised) , (handle->internal.generalTimeout * 1000), bool_false);
}

/* Entry action for state 'sendURLKeyStroke'. */
static void enact_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke(Statechart* handle)
{
	/* Entry action for state 'sendURLKeyStroke'. */
	statechart_set_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke_tev0_raised) , 100, bool_false);
	statechart_sendURLstroke(handle);
}

/* Entry action for state 'wait4RC5match'. */
static void enact_main_region_wait4RC5match(Statechart* handle)
{
	/* Entry action for state 'wait4RC5match'. */
	statechart_set_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_wait4RC5match_tev0_raised) , (handle->internal.generalTimeout * 1000), bool_false);
}

/* Entry action for state 'sendBrailleChar'. */
static void enact_main_region_sendBrailleText_r1_sendBrailleChar(Statechart* handle)
{
	/* Entry action for state 'sendBrailleChar'. */
	statechart_sendTLCbraille(handle);
}

/* Entry action for state 'wait4GyroTilt'. */
static void enact_main_region_wait4GyroTilt(Statechart* handle)
{
	/* Entry action for state 'wait4GyroTilt'. */
	statechart_set_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_wait4GyroTilt_tev0_raised) , (handle->internal.generalTimeout * 1000), bool_false);
}

/* Entry action for state 'morseFinalURL'. */
static void enact_main_region_morseFinalURL(Statechart* handle)
{
	/* Entry action for state 'morseFinalURL'. */
	handle->internal.morseIndex = 0;
}

/* Entry action for state 'sendMorseChar'. */
static void enact_main_region_morseFinalURL_r1_sendMorseChar(Statechart* handle)
{
	/* Entry action for state 'sendMorseChar'. */
	statechart_set_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_morseFinalURL_r1_sendMorseChar_tev0_raised) , 500, bool_false);
	statechart_sendTLCmorse(handle, handle->internal.morseIndex++);
}

/* Exit action for state 'wait4BLE'. */
static void exact_main_region_wait4BLE(Statechart* handle)
{
	/* Exit action for state 'wait4BLE'. */
	statechart_unset_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_wait4BLE_tev0_raised) );		
}

/* Exit action for state 'sendGreetingText'. */
static void exact_main_region_sendGreetingText(Statechart* handle)
{
	/* Exit action for state 'sendGreetingText'. */
	statechart_unset_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_sendGreetingText_tev0_raised) );		
}

/* Exit action for state 'sendGreetingKeyStroke'. */
static void exact_main_region_sendGreetingText_r1_sendGreetingKeyStroke(Statechart* handle)
{
	/* Exit action for state 'sendGreetingKeyStroke'. */
	statechart_unset_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_sendGreetingText_r1_sendGreetingKeyStroke_tev0_raised) );		
}

/* Exit action for state 'gracePeriod'. */
static void exact_main_region_sendGreetingText_r1_gracePeriod(Statechart* handle)
{
	/* Exit action for state 'gracePeriod'. */
	statechart_unset_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_sendGreetingText_r1_gracePeriod_tev0_raised) );		
	handle->internal.greetingIndex = 0;
}

/* Exit action for state 'sendRC5URLTextWithTouch'. */
static void exact_main_region_sendRC5URLTextWithTouch(Statechart* handle)
{
	/* Exit action for state 'sendRC5URLTextWithTouch'. */
	statechart_unset_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_sendRC5URLTextWithTouch_tev0_raised) );		
}

/* Exit action for state 'sendURLKeyStroke'. */
static void exact_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke(Statechart* handle)
{
	/* Exit action for state 'sendURLKeyStroke'. */
	statechart_unset_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke_tev0_raised) );		
}

/* Exit action for state 'wait4RC5match'. */
static void exact_main_region_wait4RC5match(Statechart* handle)
{
	/* Exit action for state 'wait4RC5match'. */
	statechart_unset_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_wait4RC5match_tev0_raised) );		
}

/* Exit action for state 'wait4GyroTilt'. */
static void exact_main_region_wait4GyroTilt(Statechart* handle)
{
	/* Exit action for state 'wait4GyroTilt'. */
	statechart_unset_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_wait4GyroTilt_tev0_raised) );		
}

/* Exit action for state 'sendMorseChar'. */
static void exact_main_region_morseFinalURL_r1_sendMorseChar(Statechart* handle)
{
	/* Exit action for state 'sendMorseChar'. */
	statechart_unset_timer(handle, (sc_eventid) &(handle->timeEvents.statechart_main_region_morseFinalURL_r1_sendMorseChar_tev0_raised) );		
}

/* 'default' enter sequence for state wait4BLE */
static void enseq_main_region_wait4BLE_default(Statechart* handle)
{
	/* 'default' enter sequence for state wait4BLE */
	enact_main_region_wait4BLE(handle);
	handle->stateConfVector[0] = Statechart_main_region_wait4BLE;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state autoShutdown */
static void enseq_main_region_autoShutdown_default(Statechart* handle)
{
	/* 'default' enter sequence for state autoShutdown */
	enact_main_region_autoShutdown(handle);
	handle->stateConfVector[0] = Statechart_main_region_autoShutdown;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state sendGreetingText */
static void enseq_main_region_sendGreetingText_default(Statechart* handle)
{
	/* 'default' enter sequence for state sendGreetingText */
	enact_main_region_sendGreetingText(handle);
	enseq_main_region_sendGreetingText_r1_default(handle);
}

/* 'default' enter sequence for state sendGreetingKeyStroke */
static void enseq_main_region_sendGreetingText_r1_sendGreetingKeyStroke_default(Statechart* handle)
{
	/* 'default' enter sequence for state sendGreetingKeyStroke */
	enact_main_region_sendGreetingText_r1_sendGreetingKeyStroke(handle);
	handle->stateConfVector[0] = Statechart_main_region_sendGreetingText_r1_sendGreetingKeyStroke;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state waitForGreetingKeystrokeSent */
static void enseq_main_region_sendGreetingText_r1_waitForGreetingKeystrokeSent_default(Statechart* handle)
{
	/* 'default' enter sequence for state waitForGreetingKeystrokeSent */
	handle->stateConfVector[0] = Statechart_main_region_sendGreetingText_r1_waitForGreetingKeystrokeSent;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state gracePeriod */
static void enseq_main_region_sendGreetingText_r1_gracePeriod_default(Statechart* handle)
{
	/* 'default' enter sequence for state gracePeriod */
	enact_main_region_sendGreetingText_r1_gracePeriod(handle);
	handle->stateConfVector[0] = Statechart_main_region_sendGreetingText_r1_gracePeriod;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state sendRC5URLTextWithTouch */
static void enseq_main_region_sendRC5URLTextWithTouch_default(Statechart* handle)
{
	/* 'default' enter sequence for state sendRC5URLTextWithTouch */
	enact_main_region_sendRC5URLTextWithTouch(handle);
	enseq_main_region_sendRC5URLTextWithTouch_r1_default(handle);
}

/* 'default' enter sequence for state sendURLKeyStroke */
static void enseq_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke_default(Statechart* handle)
{
	/* 'default' enter sequence for state sendURLKeyStroke */
	enact_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke(handle);
	handle->stateConfVector[0] = Statechart_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state wait4URLKeyStrokeSent */
static void enseq_main_region_sendRC5URLTextWithTouch_r1_wait4URLKeyStrokeSent_default(Statechart* handle)
{
	/* 'default' enter sequence for state wait4URLKeyStrokeSent */
	handle->stateConfVector[0] = Statechart_main_region_sendRC5URLTextWithTouch_r1_wait4URLKeyStrokeSent;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state wait4NextURLtouch */
static void enseq_main_region_sendRC5URLTextWithTouch_r1_wait4NextURLtouch_default(Statechart* handle)
{
	/* 'default' enter sequence for state wait4NextURLtouch */
	handle->stateConfVector[0] = Statechart_main_region_sendRC5URLTextWithTouch_r1_wait4NextURLtouch;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state wait4RC5match */
static void enseq_main_region_wait4RC5match_default(Statechart* handle)
{
	/* 'default' enter sequence for state wait4RC5match */
	enact_main_region_wait4RC5match(handle);
	handle->stateConfVector[0] = Statechart_main_region_wait4RC5match;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state sendBrailleText */
static void enseq_main_region_sendBrailleText_default(Statechart* handle)
{
	/* 'default' enter sequence for state sendBrailleText */
	enseq_main_region_sendBrailleText_r1_default(handle);
}

/* 'default' enter sequence for state sendBrailleChar */
static void enseq_main_region_sendBrailleText_r1_sendBrailleChar_default(Statechart* handle)
{
	/* 'default' enter sequence for state sendBrailleChar */
	enact_main_region_sendBrailleText_r1_sendBrailleChar(handle);
	handle->stateConfVector[0] = Statechart_main_region_sendBrailleText_r1_sendBrailleChar;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state wait4GyroTilt */
static void enseq_main_region_wait4GyroTilt_default(Statechart* handle)
{
	/* 'default' enter sequence for state wait4GyroTilt */
	enact_main_region_wait4GyroTilt(handle);
	handle->stateConfVector[0] = Statechart_main_region_wait4GyroTilt;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state morseFinalURL */
static void enseq_main_region_morseFinalURL_default(Statechart* handle)
{
	/* 'default' enter sequence for state morseFinalURL */
	enact_main_region_morseFinalURL(handle);
	enseq_main_region_morseFinalURL_r1_default(handle);
}

/* 'default' enter sequence for state sendMorseChar */
static void enseq_main_region_morseFinalURL_r1_sendMorseChar_default(Statechart* handle)
{
	/* 'default' enter sequence for state sendMorseChar */
	enact_main_region_morseFinalURL_r1_sendMorseChar(handle);
	handle->stateConfVector[0] = Statechart_main_region_morseFinalURL_r1_sendMorseChar;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state prepareNextChar */
static void enseq_main_region_morseFinalURL_r1_prepareNextChar_default(Statechart* handle)
{
	/* 'default' enter sequence for state prepareNextChar */
	handle->stateConfVector[0] = Statechart_main_region_morseFinalURL_r1_prepareNextChar;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state showFinalLaufschrift */
static void enseq_main_region_showFinalLaufschrift_default(Statechart* handle)
{
	/* 'default' enter sequence for state showFinalLaufschrift */
	enseq_main_region_showFinalLaufschrift_r1_default(handle);
}

/* 'default' enter sequence for state showLaufschrift */
static void enseq_main_region_showFinalLaufschrift_r1_showLaufschrift_default(Statechart* handle)
{
	/* 'default' enter sequence for state showLaufschrift */
	handle->stateConfVector[0] = Statechart_main_region_showFinalLaufschrift_r1_showLaufschrift;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Statechart* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* 'default' enter sequence for region r1 */
static void enseq_main_region_sendGreetingText_r1_default(Statechart* handle)
{
	/* 'default' enter sequence for region r1 */
	react_main_region_sendGreetingText_r1__entry_Default(handle);
}

/* 'default' enter sequence for region r1 */
static void enseq_main_region_sendRC5URLTextWithTouch_r1_default(Statechart* handle)
{
	/* 'default' enter sequence for region r1 */
	react_main_region_sendRC5URLTextWithTouch_r1__entry_Default(handle);
}

/* 'default' enter sequence for region r1 */
static void enseq_main_region_sendBrailleText_r1_default(Statechart* handle)
{
	/* 'default' enter sequence for region r1 */
	react_main_region_sendBrailleText_r1__entry_Default(handle);
}

/* 'default' enter sequence for region r1 */
static void enseq_main_region_morseFinalURL_r1_default(Statechart* handle)
{
	/* 'default' enter sequence for region r1 */
	react_main_region_morseFinalURL_r1__entry_Default(handle);
}

/* 'default' enter sequence for region r1 */
static void enseq_main_region_showFinalLaufschrift_r1_default(Statechart* handle)
{
	/* 'default' enter sequence for region r1 */
	react_main_region_showFinalLaufschrift_r1__entry_Default(handle);
}

/* Default exit sequence for state wait4BLE */
static void exseq_main_region_wait4BLE(Statechart* handle)
{
	/* Default exit sequence for state wait4BLE */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
	exact_main_region_wait4BLE(handle);
}

/* Default exit sequence for state autoShutdown */
static void exseq_main_region_autoShutdown(Statechart* handle)
{
	/* Default exit sequence for state autoShutdown */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state sendGreetingText */
static void exseq_main_region_sendGreetingText(Statechart* handle)
{
	/* Default exit sequence for state sendGreetingText */
	exseq_main_region_sendGreetingText_r1(handle);
	exact_main_region_sendGreetingText(handle);
}

/* Default exit sequence for state sendGreetingKeyStroke */
static void exseq_main_region_sendGreetingText_r1_sendGreetingKeyStroke(Statechart* handle)
{
	/* Default exit sequence for state sendGreetingKeyStroke */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
	exact_main_region_sendGreetingText_r1_sendGreetingKeyStroke(handle);
}

/* Default exit sequence for state waitForGreetingKeystrokeSent */
static void exseq_main_region_sendGreetingText_r1_waitForGreetingKeystrokeSent(Statechart* handle)
{
	/* Default exit sequence for state waitForGreetingKeystrokeSent */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state gracePeriod */
static void exseq_main_region_sendGreetingText_r1_gracePeriod(Statechart* handle)
{
	/* Default exit sequence for state gracePeriod */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
	exact_main_region_sendGreetingText_r1_gracePeriod(handle);
}

/* Default exit sequence for state sendRC5URLTextWithTouch */
static void exseq_main_region_sendRC5URLTextWithTouch(Statechart* handle)
{
	/* Default exit sequence for state sendRC5URLTextWithTouch */
	exseq_main_region_sendRC5URLTextWithTouch_r1(handle);
	exact_main_region_sendRC5URLTextWithTouch(handle);
}

/* Default exit sequence for state sendURLKeyStroke */
static void exseq_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke(Statechart* handle)
{
	/* Default exit sequence for state sendURLKeyStroke */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
	exact_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke(handle);
}

/* Default exit sequence for state wait4URLKeyStrokeSent */
static void exseq_main_region_sendRC5URLTextWithTouch_r1_wait4URLKeyStrokeSent(Statechart* handle)
{
	/* Default exit sequence for state wait4URLKeyStrokeSent */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state wait4NextURLtouch */
static void exseq_main_region_sendRC5URLTextWithTouch_r1_wait4NextURLtouch(Statechart* handle)
{
	/* Default exit sequence for state wait4NextURLtouch */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state wait4RC5match */
static void exseq_main_region_wait4RC5match(Statechart* handle)
{
	/* Default exit sequence for state wait4RC5match */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
	exact_main_region_wait4RC5match(handle);
}

/* Default exit sequence for state sendBrailleText */
static void exseq_main_region_sendBrailleText(Statechart* handle)
{
	/* Default exit sequence for state sendBrailleText */
	exseq_main_region_sendBrailleText_r1(handle);
}

/* Default exit sequence for state sendBrailleChar */
static void exseq_main_region_sendBrailleText_r1_sendBrailleChar(Statechart* handle)
{
	/* Default exit sequence for state sendBrailleChar */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state wait4GyroTilt */
static void exseq_main_region_wait4GyroTilt(Statechart* handle)
{
	/* Default exit sequence for state wait4GyroTilt */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
	exact_main_region_wait4GyroTilt(handle);
}

/* Default exit sequence for state morseFinalURL */
static void exseq_main_region_morseFinalURL(Statechart* handle)
{
	/* Default exit sequence for state morseFinalURL */
	exseq_main_region_morseFinalURL_r1(handle);
}

/* Default exit sequence for state sendMorseChar */
static void exseq_main_region_morseFinalURL_r1_sendMorseChar(Statechart* handle)
{
	/* Default exit sequence for state sendMorseChar */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
	exact_main_region_morseFinalURL_r1_sendMorseChar(handle);
}

/* Default exit sequence for state prepareNextChar */
static void exseq_main_region_morseFinalURL_r1_prepareNextChar(Statechart* handle)
{
	/* Default exit sequence for state prepareNextChar */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state showLaufschrift */
static void exseq_main_region_showFinalLaufschrift_r1_showLaufschrift(Statechart* handle)
{
	/* Default exit sequence for state showLaufschrift */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for region main region */
static void exseq_main_region(Statechart* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of Statechart.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_wait4BLE :
		{
			exseq_main_region_wait4BLE(handle);
			break;
		}
		case Statechart_main_region_autoShutdown :
		{
			exseq_main_region_autoShutdown(handle);
			break;
		}
		case Statechart_main_region_sendGreetingText_r1_sendGreetingKeyStroke :
		{
			exseq_main_region_sendGreetingText_r1_sendGreetingKeyStroke(handle);
			exact_main_region_sendGreetingText(handle);
			break;
		}
		case Statechart_main_region_sendGreetingText_r1_waitForGreetingKeystrokeSent :
		{
			exseq_main_region_sendGreetingText_r1_waitForGreetingKeystrokeSent(handle);
			exact_main_region_sendGreetingText(handle);
			break;
		}
		case Statechart_main_region_sendGreetingText_r1_gracePeriod :
		{
			exseq_main_region_sendGreetingText_r1_gracePeriod(handle);
			exact_main_region_sendGreetingText(handle);
			break;
		}
		case Statechart_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke :
		{
			exseq_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke(handle);
			exact_main_region_sendRC5URLTextWithTouch(handle);
			break;
		}
		case Statechart_main_region_sendRC5URLTextWithTouch_r1_wait4URLKeyStrokeSent :
		{
			exseq_main_region_sendRC5URLTextWithTouch_r1_wait4URLKeyStrokeSent(handle);
			exact_main_region_sendRC5URLTextWithTouch(handle);
			break;
		}
		case Statechart_main_region_sendRC5URLTextWithTouch_r1_wait4NextURLtouch :
		{
			exseq_main_region_sendRC5URLTextWithTouch_r1_wait4NextURLtouch(handle);
			exact_main_region_sendRC5URLTextWithTouch(handle);
			break;
		}
		case Statechart_main_region_wait4RC5match :
		{
			exseq_main_region_wait4RC5match(handle);
			break;
		}
		case Statechart_main_region_sendBrailleText_r1_sendBrailleChar :
		{
			exseq_main_region_sendBrailleText_r1_sendBrailleChar(handle);
			break;
		}
		case Statechart_main_region_wait4GyroTilt :
		{
			exseq_main_region_wait4GyroTilt(handle);
			break;
		}
		case Statechart_main_region_morseFinalURL_r1_sendMorseChar :
		{
			exseq_main_region_morseFinalURL_r1_sendMorseChar(handle);
			break;
		}
		case Statechart_main_region_morseFinalURL_r1_prepareNextChar :
		{
			exseq_main_region_morseFinalURL_r1_prepareNextChar(handle);
			break;
		}
		case Statechart_main_region_showFinalLaufschrift_r1_showLaufschrift :
		{
			exseq_main_region_showFinalLaufschrift_r1_showLaufschrift(handle);
			break;
		}
		default: break;
	}
}

/* Default exit sequence for region r1 */
static void exseq_main_region_sendGreetingText_r1(Statechart* handle)
{
	/* Default exit sequence for region r1 */
	/* Handle exit of all possible states (of Statechart.main_region.sendGreetingText.r1) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_sendGreetingText_r1_sendGreetingKeyStroke :
		{
			exseq_main_region_sendGreetingText_r1_sendGreetingKeyStroke(handle);
			break;
		}
		case Statechart_main_region_sendGreetingText_r1_waitForGreetingKeystrokeSent :
		{
			exseq_main_region_sendGreetingText_r1_waitForGreetingKeystrokeSent(handle);
			break;
		}
		case Statechart_main_region_sendGreetingText_r1_gracePeriod :
		{
			exseq_main_region_sendGreetingText_r1_gracePeriod(handle);
			break;
		}
		default: break;
	}
}

/* Default exit sequence for region r1 */
static void exseq_main_region_sendRC5URLTextWithTouch_r1(Statechart* handle)
{
	/* Default exit sequence for region r1 */
	/* Handle exit of all possible states (of Statechart.main_region.sendRC5URLTextWithTouch.r1) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke :
		{
			exseq_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke(handle);
			break;
		}
		case Statechart_main_region_sendRC5URLTextWithTouch_r1_wait4URLKeyStrokeSent :
		{
			exseq_main_region_sendRC5URLTextWithTouch_r1_wait4URLKeyStrokeSent(handle);
			break;
		}
		case Statechart_main_region_sendRC5URLTextWithTouch_r1_wait4NextURLtouch :
		{
			exseq_main_region_sendRC5URLTextWithTouch_r1_wait4NextURLtouch(handle);
			break;
		}
		default: break;
	}
}

/* Default exit sequence for region r1 */
static void exseq_main_region_sendBrailleText_r1(Statechart* handle)
{
	/* Default exit sequence for region r1 */
	/* Handle exit of all possible states (of Statechart.main_region.sendBrailleText.r1) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_sendBrailleText_r1_sendBrailleChar :
		{
			exseq_main_region_sendBrailleText_r1_sendBrailleChar(handle);
			break;
		}
		default: break;
	}
}

/* Default exit sequence for region r1 */
static void exseq_main_region_morseFinalURL_r1(Statechart* handle)
{
	/* Default exit sequence for region r1 */
	/* Handle exit of all possible states (of Statechart.main_region.morseFinalURL.r1) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_morseFinalURL_r1_sendMorseChar :
		{
			exseq_main_region_morseFinalURL_r1_sendMorseChar(handle);
			break;
		}
		case Statechart_main_region_morseFinalURL_r1_prepareNextChar :
		{
			exseq_main_region_morseFinalURL_r1_prepareNextChar(handle);
			break;
		}
		default: break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_wait4BLE_default(handle);
}

/* Default react sequence for initial entry  */
static void react_main_region_sendGreetingText_r1__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_sendGreetingText_r1_gracePeriod_default(handle);
}

/* Default react sequence for initial entry  */
static void react_main_region_sendRC5URLTextWithTouch_r1__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke_default(handle);
}

/* Default react sequence for initial entry  */
static void react_main_region_sendBrailleText_r1__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_sendBrailleText_r1_sendBrailleChar_default(handle);
}

/* Default react sequence for initial entry  */
static void react_main_region_morseFinalURL_r1__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_morseFinalURL_r1_sendMorseChar_default(handle);
}

/* Default react sequence for initial entry  */
static void react_main_region_showFinalLaufschrift_r1__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_showFinalLaufschrift_r1_showLaufschrift_default(handle);
}


static sc_boolean react(Statechart* handle)
{
	/* State machine reactions. */
	SC_UNUSED(handle);
	return bool_false;
}

static sc_boolean main_region_wait4BLE_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state wait4BLE. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->iface.BLEconnected_raised == bool_true)
		{ 
			exseq_main_region_wait4BLE(handle);
			enseq_main_region_sendGreetingText_default(handle);
			react(handle);
		}  else
		{
			if (handle->timeEvents.statechart_main_region_wait4BLE_tev0_raised == bool_true)
			{ 
				exseq_main_region_wait4BLE(handle);
				enseq_main_region_autoShutdown_default(handle);
				react(handle);
			}  else
			{
				did_transition = bool_false;
			}
		}
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} return did_transition;
}

static sc_boolean main_region_autoShutdown_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state autoShutdown. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		did_transition = bool_false;
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} return did_transition;
}

static sc_boolean main_region_sendGreetingText_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state sendGreetingText. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->iface.BLEdisconnected_raised == bool_true)
		{ 
			exseq_main_region_sendGreetingText(handle);
			enseq_main_region_autoShutdown_default(handle);
			react(handle);
		}  else
		{
			if (handle->timeEvents.statechart_main_region_sendGreetingText_tev0_raised == bool_true)
			{ 
				exseq_main_region_sendGreetingText(handle);
				enseq_main_region_autoShutdown_default(handle);
				react(handle);
			}  else
			{
				if (handle->iface.TouchIRQ_raised == bool_true)
				{ 
					exseq_main_region_sendGreetingText(handle);
					enseq_main_region_sendRC5URLTextWithTouch_default(handle);
					react(handle);
				}  else
				{
					did_transition = bool_false;
				}
			}
		}
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} return did_transition;
}

static sc_boolean main_region_sendGreetingText_r1_sendGreetingKeyStroke_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state sendGreetingKeyStroke. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->timeEvents.statechart_main_region_sendGreetingText_r1_sendGreetingKeyStroke_tev0_raised == bool_true)
		{ 
			exseq_main_region_sendGreetingText_r1_sendGreetingKeyStroke(handle);
			enseq_main_region_sendGreetingText_r1_waitForGreetingKeystrokeSent_default(handle);
			main_region_sendGreetingText_react(handle, bool_false);
		}  else
		{
			did_transition = bool_false;
		}
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = main_region_sendGreetingText_react(handle, try_transition);
	} return did_transition;
}

static sc_boolean main_region_sendGreetingText_r1_waitForGreetingKeystrokeSent_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state waitForGreetingKeystrokeSent. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (((handle->iface.KBDstrokeSent_raised) == bool_true) && (((handle->internal.greetingIndex) < (statechart_getKBDstringLength(handle, 0))) == bool_true))
		{ 
			exseq_main_region_sendGreetingText_r1_waitForGreetingKeystrokeSent(handle);
			enseq_main_region_sendGreetingText_r1_sendGreetingKeyStroke_default(handle);
			main_region_sendGreetingText_react(handle, bool_false);
		}  else
		{
			if (((handle->iface.KBDstrokeSent_raised) == bool_true) && (((handle->internal.greetingIndex) >= (statechart_getKBDstringLength(handle, 0))) == bool_true))
			{ 
				exseq_main_region_sendGreetingText_r1_waitForGreetingKeystrokeSent(handle);
				enseq_main_region_sendGreetingText_r1_gracePeriod_default(handle);
				main_region_sendGreetingText_react(handle, bool_false);
			}  else
			{
				did_transition = bool_false;
			}
		}
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = main_region_sendGreetingText_react(handle, try_transition);
	} return did_transition;
}

static sc_boolean main_region_sendGreetingText_r1_gracePeriod_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state gracePeriod. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->timeEvents.statechart_main_region_sendGreetingText_r1_gracePeriod_tev0_raised == bool_true)
		{ 
			exseq_main_region_sendGreetingText_r1_gracePeriod(handle);
			enseq_main_region_sendGreetingText_r1_sendGreetingKeyStroke_default(handle);
			main_region_sendGreetingText_react(handle, bool_false);
		}  else
		{
			did_transition = bool_false;
		}
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = main_region_sendGreetingText_react(handle, try_transition);
	} return did_transition;
}

static sc_boolean main_region_sendRC5URLTextWithTouch_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state sendRC5URLTextWithTouch. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->timeEvents.statechart_main_region_sendRC5URLTextWithTouch_tev0_raised == bool_true)
		{ 
			exseq_main_region_sendRC5URLTextWithTouch(handle);
			enseq_main_region_autoShutdown_default(handle);
			react(handle);
		}  else
		{
			if (handle->iface.URLstringDone_raised == bool_true)
			{ 
				exseq_main_region_sendRC5URLTextWithTouch(handle);
				enseq_main_region_wait4RC5match_default(handle);
				react(handle);
			}  else
			{
				did_transition = bool_false;
			}
		}
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} return did_transition;
}

static sc_boolean main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state sendURLKeyStroke. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->timeEvents.statechart_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke_tev0_raised == bool_true)
		{ 
			exseq_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke(handle);
			enseq_main_region_sendRC5URLTextWithTouch_r1_wait4URLKeyStrokeSent_default(handle);
			main_region_sendRC5URLTextWithTouch_react(handle, bool_false);
		}  else
		{
			did_transition = bool_false;
		}
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = main_region_sendRC5URLTextWithTouch_react(handle, try_transition);
	} return did_transition;
}

static sc_boolean main_region_sendRC5URLTextWithTouch_r1_wait4URLKeyStrokeSent_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state wait4URLKeyStrokeSent. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->iface.KBDstrokeSent_raised == bool_true)
		{ 
			exseq_main_region_sendRC5URLTextWithTouch_r1_wait4URLKeyStrokeSent(handle);
			enseq_main_region_sendRC5URLTextWithTouch_r1_wait4NextURLtouch_default(handle);
			main_region_sendRC5URLTextWithTouch_react(handle, bool_false);
		}  else
		{
			did_transition = bool_false;
		}
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = main_region_sendRC5URLTextWithTouch_react(handle, try_transition);
	} return did_transition;
}

static sc_boolean main_region_sendRC5URLTextWithTouch_r1_wait4NextURLtouch_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state wait4NextURLtouch. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->iface.TouchIRQ_raised == bool_true)
		{ 
			exseq_main_region_sendRC5URLTextWithTouch_r1_wait4NextURLtouch(handle);
			enseq_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke_default(handle);
			main_region_sendRC5URLTextWithTouch_react(handle, bool_false);
		}  else
		{
			did_transition = bool_false;
		}
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = main_region_sendRC5URLTextWithTouch_react(handle, try_transition);
	} return did_transition;
}

static sc_boolean main_region_wait4RC5match_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state wait4RC5match. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->timeEvents.statechart_main_region_wait4RC5match_tev0_raised == bool_true)
		{ 
			exseq_main_region_wait4RC5match(handle);
			enseq_main_region_autoShutdown_default(handle);
			react(handle);
		}  else
		{
			if (handle->iface.RC5match_raised == bool_true)
			{ 
				exseq_main_region_wait4RC5match(handle);
				enseq_main_region_sendBrailleText_default(handle);
				react(handle);
			}  else
			{
				did_transition = bool_false;
			}
		}
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} return did_transition;
}

static sc_boolean main_region_sendBrailleText_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state sendBrailleText. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->iface.brailleStringDone_raised == bool_true)
		{ 
			exseq_main_region_sendBrailleText(handle);
			enseq_main_region_wait4GyroTilt_default(handle);
			react(handle);
		}  else
		{
			did_transition = bool_false;
		}
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} return did_transition;
}

static sc_boolean main_region_sendBrailleText_r1_sendBrailleChar_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state sendBrailleChar. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->iface.brailleCharSent_raised == bool_true)
		{ 
			exseq_main_region_sendBrailleText_r1_sendBrailleChar(handle);
			enseq_main_region_sendBrailleText_r1_sendBrailleChar_default(handle);
			main_region_sendBrailleText_react(handle, bool_false);
		}  else
		{
			did_transition = bool_false;
		}
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = main_region_sendBrailleText_react(handle, try_transition);
	} return did_transition;
}

static sc_boolean main_region_wait4GyroTilt_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state wait4GyroTilt. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->timeEvents.statechart_main_region_wait4GyroTilt_tev0_raised == bool_true)
		{ 
			exseq_main_region_wait4GyroTilt(handle);
			enseq_main_region_autoShutdown_default(handle);
			react(handle);
		}  else
		{
			if (handle->iface.GYROtilt_raised == bool_true)
			{ 
				exseq_main_region_wait4GyroTilt(handle);
				enseq_main_region_morseFinalURL_default(handle);
				react(handle);
			}  else
			{
				did_transition = bool_false;
			}
		}
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} return did_transition;
}

static sc_boolean main_region_morseFinalURL_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state morseFinalURL. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->iface.morseStringDone_raised == bool_true)
		{ 
			exseq_main_region_morseFinalURL(handle);
			enseq_main_region_showFinalLaufschrift_default(handle);
			react(handle);
		}  else
		{
			did_transition = bool_false;
		}
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} return did_transition;
}

static sc_boolean main_region_morseFinalURL_r1_sendMorseChar_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state sendMorseChar. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if (handle->timeEvents.statechart_main_region_morseFinalURL_r1_sendMorseChar_tev0_raised == bool_true)
		{ 
			exseq_main_region_morseFinalURL_r1_sendMorseChar(handle);
			enseq_main_region_morseFinalURL_r1_prepareNextChar_default(handle);
			main_region_morseFinalURL_react(handle, bool_false);
		}  else
		{
			did_transition = bool_false;
		}
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = main_region_morseFinalURL_react(handle, try_transition);
	} return did_transition;
}

static sc_boolean main_region_morseFinalURL_r1_prepareNextChar_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state prepareNextChar. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		exseq_main_region_morseFinalURL_r1_prepareNextChar(handle);
		enseq_main_region_morseFinalURL_r1_sendMorseChar_default(handle);
		main_region_morseFinalURL_react(handle, bool_false);
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = main_region_morseFinalURL_react(handle, try_transition);
	} return did_transition;
}

static sc_boolean main_region_showFinalLaufschrift_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state showFinalLaufschrift. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		did_transition = bool_false;
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = react(handle);
	} return did_transition;
}

static sc_boolean main_region_showFinalLaufschrift_r1_showLaufschrift_react(Statechart* handle, const sc_boolean try_transition)
{
	/* The reactions of state showLaufschrift. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		did_transition = bool_false;
	} if ((did_transition) == (bool_false))
	{ 
		did_transition = main_region_showFinalLaufschrift_react(handle, try_transition);
	} return did_transition;
}




static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq)
{
	return eq->size;
}

static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq)
{
	statechart_event event;
	if(statechart_eventqueue_size(eq) <= 0) {
		statechart_event_init(&event, Statechart_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev)
{
	if(statechart_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void statechart_event_init(statechart_event * ev, StatechartEventID name)
{
	ev->name = name;
	ev->has_value = bool_false;
}

static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name)
{
	statechart_event event;
	statechart_event_init(&event, name);
	statechart_eventqueue_push(eq, event);
}

static void statechart_dispatch_event(Statechart* handle, const statechart_event * event) {
	switch(event->name) {
		case Statechart_BLEconnected:
		{
			handle->iface.BLEconnected_raised = bool_true;
			break;
		}
		case Statechart_BLEdisconnected:
		{
			handle->iface.BLEdisconnected_raised = bool_true;
			break;
		}
		case Statechart_TouchIRQ:
		{
			handle->iface.TouchIRQ_raised = bool_true;
			break;
		}
		case Statechart_KBDstrokeSent:
		{
			handle->iface.KBDstrokeSent_raised = bool_true;
			break;
		}
		case Statechart_URLstringDone:
		{
			handle->iface.URLstringDone_raised = bool_true;
			handle->iface.URLstringDone_value = event->value.Statechart_URLstringDone_value;
			break;
		}
		case Statechart_RC5match:
		{
			handle->iface.RC5match_raised = bool_true;
			break;
		}
		case Statechart_brailleCharSent:
		{
			handle->iface.brailleCharSent_raised = bool_true;
			break;
		}
		case Statechart_brailleStringDone:
		{
			handle->iface.brailleStringDone_raised = bool_true;
			break;
		}
		case Statechart_GYROtilt:
		{
			handle->iface.GYROtilt_raised = bool_true;
			break;
		}
		case Statechart_morseStringDone:
		{
			handle->iface.morseStringDone_raised = bool_true;
			break;
		}
		case Statechart_Statechart_main_region_wait4BLE_time_event_0:
		{
			handle->timeEvents.statechart_main_region_wait4BLE_tev0_raised = bool_true;
			break;
		}
		case Statechart_Statechart_main_region_sendGreetingText_time_event_0:
		{
			handle->timeEvents.statechart_main_region_sendGreetingText_tev0_raised = bool_true;
			break;
		}
		case Statechart_Statechart_main_region_sendGreetingText_r1_sendGreetingKeyStroke_time_event_0:
		{
			handle->timeEvents.statechart_main_region_sendGreetingText_r1_sendGreetingKeyStroke_tev0_raised = bool_true;
			break;
		}
		case Statechart_Statechart_main_region_sendGreetingText_r1_gracePeriod_time_event_0:
		{
			handle->timeEvents.statechart_main_region_sendGreetingText_r1_gracePeriod_tev0_raised = bool_true;
			break;
		}
		case Statechart_Statechart_main_region_sendRC5URLTextWithTouch_time_event_0:
		{
			handle->timeEvents.statechart_main_region_sendRC5URLTextWithTouch_tev0_raised = bool_true;
			break;
		}
		case Statechart_Statechart_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke_time_event_0:
		{
			handle->timeEvents.statechart_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke_tev0_raised = bool_true;
			break;
		}
		case Statechart_Statechart_main_region_wait4RC5match_time_event_0:
		{
			handle->timeEvents.statechart_main_region_wait4RC5match_tev0_raised = bool_true;
			break;
		}
		case Statechart_Statechart_main_region_wait4GyroTilt_time_event_0:
		{
			handle->timeEvents.statechart_main_region_wait4GyroTilt_tev0_raised = bool_true;
			break;
		}
		case Statechart_Statechart_main_region_morseFinalURL_r1_sendMorseChar_time_event_0:
		{
			handle->timeEvents.statechart_main_region_morseFinalURL_r1_sendMorseChar_tev0_raised = bool_true;
			break;
		}
		default:
			break;
	}
}

static statechart_event statechart_get_next_event(Statechart* handle)
{
	statechart_event next_event;
	statechart_event_init(&next_event, Statechart_invalid_event);
	if(statechart_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = statechart_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static void statechart_dispatch_next_event(Statechart* handle)
{
	statechart_event nextEvent;
	nextEvent = statechart_get_next_event(handle);
	statechart_dispatch_event(handle, &nextEvent);
}

static StatechartEventID statechart_get_timed_event_name(Statechart* handle, sc_eventid evid)
{
	if(evid == &handle->timeEvents.statechart_main_region_wait4BLE_tev0_raised) {
		return Statechart_Statechart_main_region_wait4BLE_time_event_0;
	}
	if(evid == &handle->timeEvents.statechart_main_region_sendGreetingText_tev0_raised) {
		return Statechart_Statechart_main_region_sendGreetingText_time_event_0;
	}
	if(evid == &handle->timeEvents.statechart_main_region_sendGreetingText_r1_sendGreetingKeyStroke_tev0_raised) {
		return Statechart_Statechart_main_region_sendGreetingText_r1_sendGreetingKeyStroke_time_event_0;
	}
	if(evid == &handle->timeEvents.statechart_main_region_sendGreetingText_r1_gracePeriod_tev0_raised) {
		return Statechart_Statechart_main_region_sendGreetingText_r1_gracePeriod_time_event_0;
	}
	if(evid == &handle->timeEvents.statechart_main_region_sendRC5URLTextWithTouch_tev0_raised) {
		return Statechart_Statechart_main_region_sendRC5URLTextWithTouch_time_event_0;
	}
	if(evid == &handle->timeEvents.statechart_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke_tev0_raised) {
		return Statechart_Statechart_main_region_sendRC5URLTextWithTouch_r1_sendURLKeyStroke_time_event_0;
	}
	if(evid == &handle->timeEvents.statechart_main_region_wait4RC5match_tev0_raised) {
		return Statechart_Statechart_main_region_wait4RC5match_time_event_0;
	}
	if(evid == &handle->timeEvents.statechart_main_region_wait4GyroTilt_tev0_raised) {
		return Statechart_Statechart_main_region_wait4GyroTilt_time_event_0;
	}
	if(evid == &handle->timeEvents.statechart_main_region_morseFinalURL_r1_sendMorseChar_tev0_raised) {
		return Statechart_Statechart_main_region_morseFinalURL_r1_sendMorseChar_time_event_0;
	}
	return Statechart_invalid_event;
}


static void statechart_event_value_init(statechart_event * ev, StatechartEventID name, void * value)
{
	ev->name = name;
	ev->has_value = bool_true;
	
	switch(name)
	{
		case Statechart_URLstringDone:
			ev->value.Statechart_URLstringDone_value = *((sc_integer*)value);
			break;
		default:
			break;
	}
}

static void statechart_add_value_event_to_queue(statechart_eventqueue * eq, StatechartEventID name, void * value)
{
	statechart_event event;
	statechart_event_value_init(&event, name, value);
	statechart_eventqueue_push(eq, event);
}
